### ISSUE TITLE
Add Github Auth

### ISSUE THREAD

**Issue by reaaz** [maxwfreu/Pancake#1]
# Description
Need to add Github authentication to be able to have a user auth and select a repo.

# Tasks
- [ ] Create Github app
- [ ] Add Github OAuth flow with correct scopes
- [ ] Verify we can pull issues after auth'd
