### ISSUE TITLE
UI: Create action bar for cards

### ISSUE THREAD

**Issue by maxwfreu** [maxwfreu/Pancake#2]
# Description
Create the Github link, modal trigger, and size dropdown for cards. The size picker should be reusable as it will be needed inside modals.

# Tasks
- [x] Create Github Link
- [x] Create modal button
- [x] Create reusable size picker
